spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.91.131:3306/blog?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
# 日志配置
logging:
  level:
    root: warn
    com.colm.blog: info
  file:
    path: log/
    name: blog-prod.log
server:
  port: 8081